import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { Lexend } from 'next/font/google'
import './globals.css'

const lexendFont = Lexend({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-lexend',
})

export const metadata: Metadata = {
	title: 'Flashglass',
	description: 'Generated by flashglass',
}

export function generateStaticParams() {
	return [{ locale: 'en' }, { locale: 'fr' }]
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode
	params: Promise<{ locale: string }>
}>) {
	const { locale } = await params

	// Enable static rendering
	setRequestLocale(locale)

	// Providing all messages to the client
	// side is the easiest way to get started
	const messages = await getMessages()

	return (
		<html lang={locale}>
			<body className={`relative ${lexendFont.className} antialiased`}>
				<NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
				<Toaster />
			</body>
		</html>
	)
}
